spring:
    datasource:
        
        username: amanda
        password: 123trocar
        url: jdbc:mysql://pridedevdatabase.c3lbe0bvk2jp.us-east-1.rds.amazonaws.com/amanda
         
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
