
spring.datasource.username=amanda;
spring.datasource.password=123trocar;
spring.datasource.url=jdbc:mysql://pridedevdatabase.c3lbe0bvk2jp.us-east-1.rds.amazonaws.com/amanda;
spring.jpa.hibernate.ddl-auto= update;

